#Get all categories
GET http://localhost:3000/api/categories
X-API-KEY: SECRET
Accept: application/json

### Create New Category
POST http://localhost:3000/api/categories
X-API-KEY: SECRET
Accept: application/json
Content-Type: application/json

{
  "name":"Software"
}

### GET category by Id
GET http://localhost:3000/api/categories/16
X-API-KEY: SECRET
Accept: application/json

### Update Category By Id
PUT http://localhost:3000/api/categories/16
X-API-KEY: SECRET
Content-Type: application/json
Accept: application/json

{
  "name": "Software dan OS"
}

### Delete category by Id
DELETE http://localhost:3000/api/categories/16
X-API-KEY: SECRET
Accept: application/json